### ISSUE TITLE
Exemplify ATO process with simpler standards/certifications

### ISSUE THREAD

**Issue by pburkholder** [pburkholder/ato1day-compliance#1]
Assuming a fictional nation of Freedonia, 
- standards of FIST-1 with, say 3 controls in 2 families, including technical controls and organizational controls, and 
- a certification of FreeLow that reference back to that.

Write an ideal SSP

Use opencontrol, compliance-masonry to generate something close to the ideal SSP.

**Comment by pburkholder** [comment]
Remove Epic label -- this is either an issue or a wiki page describing where I'm going.

**Comment by pburkholder** [comment]
This is not an actionable issue.

**Comment by afeld** [comment]
I like the idea of making a minimal (fake) certification for demonstration purposes.

**Comment by pburkholder** [comment]
@afeld Yup, the fictional compliance/SSP is what I'm working on with this project and freedonia-compliance. I just closed this particular issue because it wasn't useful as a guide to my work.
